### resource not found
GET http://localhost:3000/api/null

###
###AUTEURS###
###

### Récupération des tous les auteurs
GET http://localhost:3000/api/authors

### Récupération d'un auteur
GET http://localhost:3000/api/authors/1

### Ajout d'auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstname": "Jules",
    "lastname": "Verne",
    "country_iso_2": "fr",
    "birthdate": "1828-02-08",
    "deathdate": "1905-03-24"
}

### Update d'auteur
PATCH http://localhost:3000/api/authors/6
Content-Type: application/json

{
    "country_iso_2": "fr"
}

### delete d'auteur
DELETE http://localhost:3000/api/authors/5




###
###EDITEURS###
###

### Récupération des tous les éditeurs
GET http://localhost:3000/api/publishers

### Ajout d'un publisher
POST http://localhost:3000/api/publishers
Content-Type: application/json

{
    "name": "Plon",
    "country_iso_2": "fr"
}

### Récupération d'un éditeur 
GET http://localhost:3000/api/publishers/1

### Update d'un éditeur OK
PATCH http://localhost:3000/api/publishers/4
Content-Type: application/json

{
    "name": "Plon"
}

### delete d'un éditeur OK
DELETE http://localhost:3000/api/publishers/4


###
###GENRES###
###

### Récupération des tous les genre
GET http://localhost:3000/api/genre

### Ajout d'un genre
POST http://localhost:3000/api/genre
Content-Type: application/json

{
    "label": "Roman"
}


###
###LIVRES###
###

### Récupération de tous les livres
GET http://localhost:3000/api/books

### Récupération de tous les livres
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "reference": "2661",
    "title": "Le seigneur des anneaux : le retour de la reine",
    "locale": "fr_FR",
    "year": 1966,
    "page_count": 600,
    "chapter_count": 0,
    "front_cover": "NA",
    "cover": null,
    "publisher_id": 2,
    "created_at": "2021-05-18T11:59:08.096Z",
    "updated_at": null,
    "deleted_at": null,
    "genre_id": [2],
    "author_id": [1,2]
}


### Récupération d'un livre
GET http://localhost:3000/api/books/2

### Update d'un livre
PATCH http://localhost:3000/api/books/2
Content-Type: application/json

{
    "year": "1996"
}

### delete d'un livre
DELETE http://localhost:3000/api/books/1